package: insert_text
version: '1.2.0'
name: Insert Text
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/redaxo-insert_text

requires:
    redaxo: '^5.0'
    packages:
        media_manager: '^2.5'
