package: insert_text
version: "2.0.1"
name: Insert Text
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/insert_text

requires:
  php: ">=7.2.5"
  redaxo: ">=5.0"
  packages:
    media_manager: ">=2.5"
